Chia-Network/pool-reference

- pool/pool_server.py
added support for CORS (Access-Control-Allow-Origin: *)
> allow cors for GUI and other applications

- setup.py
> Fixed Typo

- README.md
fixed `chia wallet show` markdown in the documentation.
> fixed `chia wallet show` markdown

- pool/pool.py
To fix the use of payment_interval variables.
> To fix the use of payment_interval variables.

- README.md
- config.yaml
- pool/pool.py
- pool/pool_server.py
This should make it slightly easier for pool operators to change config bits while testing and tweaking their pools.  Let me know if this may be helpful or if we should include or exclude anything else.
> Added yaml configuration file for some of the important pool configuration parts

- config.yaml
- pool/pool.py
- pool/singleton.py
- pool/store.py
Separates partials and farmer creation into different endpoints.
Note: 
* This corresponds to the pools.dev in chia-blockchain.
* This is a breaking change to singletons, plot format for singletons, and the DB. Everything must be created from scratch
> Pr split partials

- pool/pool.py
FarmerRecord.from_json_dict(farmer_dict) won't work as FarmerRecord has "difficulty" but not "suggested_difficulty"
> Fix FarmerRecord "suggested_difficulty" in update_farmer

- pool/pool.py
- pool/singleton.py
> pool|singleton: Fix and improve singleton state processing

- README.md
changed step 1 for testnet 9
polish on step 7
added `-s pool` on step 8
> Updating README.MD install for testnet9, steps 1. 7. 8. modified to reflect changes

- config-example.yaml
- pool/pool.py
Useful when running pool server in daemon
> Add logging to file option

- pool/pool.py
Our poll will feature, among other things, a custom difficulty adjustment function. The default one may be good for most cases, but we'd like to alter it a little bit. At the same time, we don't want to move too far away from the reference implementation - thus we'd like to have a way of providing not just our custom `pool_store`, but also the difficulty adjustment function for the pools that we create. This 5 LOC PR provides such possibility.
> Allow passing custom difficulty function to the Pool class

- pool/singleton.py
> singleton: Fix `validate_puzzle_hash` in `get_singleton_state`

- pool/pool_server.py
> feat: serve forever

- README.md
- pool/pool_server.py
Such a change allows developers using the pool_Server code to easily implement their own logic, without having to copy the authentication part
> get_login split into an authentication part and a response part to allow customization

- pool/pool.py
- pool/singleton.py
* Only absorb coinbase rewards
* Only payout when we have more than 1.75+ (to avoid forcing payouts with small spam mojos)
> Ms.only coinbase

- pool/difficulty_adjustment.py
- tests/test_difficulty.py
> Adjust difficulty at least once a day (time_target).

- config-example.yaml
- pool/pool.py
- pool/pool_server.py
> pool: Support TLS

- pool/pool.py
- pool/store/mariadb_store.py
@ppolewicz  Convinced me to make this pull request 
I didn't want to over complicate it so i simply  stripped out my personal pool code and added what was needed and only what was needed to use the store.
> add mariadb store and store adjustment through config.yaml

- pool/pool.py
With this code change aiomysql is no longer a needed dependency.
> move import so that aiomysql is not needed to start

- pool/store/sqlite_store.py
farmer request pool "post_farmer", "put_farmer" RPC interface, causing points to be replace by historical data.
> Bug Fix: Inaccurate points update！

- pool/pool.py
> pool: Fix some issues in `PUT /farmer`

- pool/pool.py
This was changed in https://github.com/Chia-Network/chia-blockchain/pull/13930.
> pool: Fix partial validation
